pipeline:
  push-latest:
    image: plugins/docker
    settings:
      repo: nvdk/lblod-scraper
      tags: latest
      purge: true
    secrets: [docker_username, docker_password]
when:
  branch: master
  event: [push, tag, deployment]
